### ISSUE TITLE
lodash error

### ISSUE THREAD

**Issue by asaupup** [blakgeek/cordova-plugin-cocoapods-support#22]
Executing script found in plugin cordova-plugin-cocoapod-support for hook "after_prepare": plugins/cordova-plugin-cocoapod-support/scripts/podify.js
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/asaup/site-home/io.nuwa.live.hx.app/plugins/cordova-plugin-cocoapod-support/scripts/podify.js:3:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by asaupup** [comment]
Error: ENOENT: no such file or directory, open 'platforms/ios/Pods/Target Support Files/Pods-mydemoapp/Pods-mydemoapp-resources.sh'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at fixBundlePaths (/Users/asaup/site-home/io.nuwa.live.hx.app/plugins/cordova-plugin-cocoapod-support/scripts/podify.js:224:30)
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by asaupup** [comment]
MY plugin.xml is : 
```xml
<pods-config ios-min-version="8.0" uses-frameworks="true" />
        <!--
        <pod id="LatestPod" />
        <pod id="VersionedPod" version="1.0.0" />
        -->
        <pod id="LFLiveKit" />
        <pod id="PLPlayerKit" />
        <!--
        <pod id="BadBundle" fix-bundle-path="Bad/Path.bundle"/>
        -->
```

and my command is : 
```
cordova plugin remove io.nuwa.live.app.sdk.plugin --verbose && cordova plugin add ../io.nuwa.live.app.sdk.plugin --verbose && cordova platform remove ios --verbose && cordova platform add ios --verbose && cordova prepare --verbose
```

**Comment by jaygauten** [comment]
@blakgeek i didn't get what was posted here, but im experiencing the same issue as @asaupup 

can you share how to fix the lodash module not found error?
