### ISSUE TITLE
Build failed. Xcode module not found.

### ISSUE THREAD

**Issue by ilyakar** [blakgeek/cordova-plugin-cocoapods-support#30]
Error: Cannot find module '../../node_modules/xcode'

Cordova v6.5.0

**Comment by blakgeek** [comment]
Can you run with --verbose and post a gist of the output?

**Comment by thedmeyer** [comment]
I got the following:

```
Checking config.xml for pods.

No new pods detects

Executing script found in plugin cordova-plugin-firebase-hooks for hook "after_prepare": plugins/cordova-plugin-firebase-hooks/hooks/ios/copy-google-services.js

Resolving module name for cordova-lib/node_modules/xcode => ../../node_modules/xcode

Error: Cannot find module '../../node_modules/xcode'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:77:12)
    at module.exports (/Users/thedmeyer/GitHub/Flatiron/ionic_tester/plugins/cordova-plugin-firebase-hooks/hooks/ios/copy-google-services.js:6:23)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:187:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
```
